### ISSUE TITLE
Enhancement  Request

### ISSUE THREAD

**Issue by v-dale** [ClassicOldSong/vue-simple-i18n#2]
Hi
first I'd like to thank you for this awesome plugin, it's about exactly what I was looking for. But I have one issue. I'm using vue with webpack and I want to use this as a global plugin to all the components, so that each component has it's own local data and info and if there is something which is used globally I put it in the main.js or the plugin folder itself. but I'm struggling with it. I don't know how to achieve it.

this is what I'm trying to do:
```js
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import vI18n from 'vue-simple-i18n'


createApp(App)
    .use(store)
    .use(router)
    .use(vI18n)
    .mount('#app')
```

but it seems that the library doesn't support it.

I can import it in each component and define the content like this
```js
const i18n = new vI18n({
  base: 'en-us', // The base fallback when specified language not exists, defaults to 'en-us'
  locale: 'zh-cn', // Global language, defaults to browser language
  locales: {
    'en-us': {
      __name__: 'English', // Specify a display name for each language is highly recommended
      welcome: 'Welcome {{name}} to the Wonderland!' // Translation, default template supported is vue-like without expressions
    },
    'zh-cn': {
      __name__: '简体中文',
      welcome: '{{name}}，欢迎来到幻境！'
    }
  } // Where you put all your translations
})


computed: {
    ...i18n.map(['welcome']) // Map the translation!
  }
```

But there must be some other ways. moving the `base` and `locale` to the main.js and in the `data` define the locals

so that the component becomes like this:

```js

export default{
  data(){
     return(){
         locales:{
            'en-us':{welcome: 'Welcome {{name}} to the Wonderland!'},
            'zh-cn':{welcome: '{{name}}，欢迎来到幻境！'} 
        }
    }
  }
}
```

that would be awesome  :)

**Comment by ClassicOldSong** [comment]
First of all thank you for paying attention to this plugin, but I'm sorry
that this plugin is not supposed to work the way you intended it to be.

For some reason I'm no longer a fan of Vue.js and will no longer contribute
to Vue.js development. You could scratch your own itch by writing a wrapper
for it. You may refer to this document for creating your own plugin:
https://vuejs.org/v2/guide/plugins.html#Writing-a-Plugin

I've created a totally different flavoured front-end framework
https://github.com/TheNeuronProject/ef.js , which you could take a look if
you're interested in something simple and timeless.

**Comment by v-dale** [comment]
Thanks for your reply

It's amazing, you have created your own framework. wish you all the best 🙏🏼
